#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="/usr/bin/eww -c $HOME/dotfiles/eww"

## Open widgets 
run_eww() {
	${EWW} open-many bar
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww && bspc config -m HDMI-0 top_padding 49
else
	${EWW} close-all #&& killall eww
	rm "$FILE" && bspc config -m HDMI-0 top_padding 0
fi
