#!/bin/sh

bspc config top_padding 0

# programs
pgrep -x sxhkd > /dev/null || sxhkd -c ~/dotfiles/sxhkd/sxhkdrc &
pgrep -x dunst > /dev/null || dunst -conf ~/dotfiles/dunst/dunstrc &
pgrep -x picom > /dev/null || picom --config ~/dotfiles/picom/picom.conf --experimental-backends &
# polybar -c ~/dotfiles/polybar/config.ini skye && killall polybar && polybar -c ~/dotfiles/polybar/config.ini skye &
eww daemon
/usr/lib/polkit-kde-authentication-agent-1 &
pgrep -x activate-linux > /dev/null || ~/misc/activate-linux/bin/activate-linux "Touch Grass" "Go outside to touch grass." &
pulseaudio &

# misc
redshift -PO 6000

# bspwm config
bspc config focus_follows_pointer true
bspc config window_gap 6

# workspaces
bspc monitor DP-3 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 1 2 3 4 5

# bspwm rules
bspc rule -a zoom state=floating center=on follow=on border=off

# dracula - change this to catppuccin at some point
bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

xwallpaper --stretch ~/dotfiles/wallpapers/nebula.jpg

~/dotfiles/eww/launch_bar
