#!/bin/bash
# scripts by adi1090x, modified by lisenaaaa

## Get data
STATUS="$(playerctl --player=spotify status)"
COVER="/tmp/.music_cover.png"
MUSIC_DIR="$HOME/Music"

## Get status
get_status() {
	if [[ $STATUS == "Playing" ]]; then
		echo ""
	else
		echo "契"
	fi
}

## Get song
get_song() {
	song=`playerctl --player=spotify metadata xesam:title`
	# song="long title"
  if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=`playerctl --player=spotify metadata xesam:artist`
	if [[ -z "$artist" ]]; then
		echo ""
	else
		echo "$artist"
	fi	
}

## Get time
get_time() {
	time=`playerctl metadata --format "{{ duration(position) }}" --player=spotify`
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi	
}
get_ctime() {
	ctime=`playerctl metadata --format "{{ duration(position) }}" --player=spotify`
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi	
}
get_ttime() {
	ttime=`playerctl metadata --format "{{ duration(position) }}" --player=spotify`
	if [[ -z "$ttime" ]]; then
		echo "0:00"
	else
		echo "$ttime"
	fi	
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--toggle" ]]; then
	playerctl --player=spotify play-pause
elif [[ "$1" == "--next" ]]; then
	{ playerctl --player=spotify next; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ playerctl --player=spotify previous; get_cover; }
fi
